spring:
  profiles:
    active:
      - dev
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    contexts: dev,test-data
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://localhost:5432/investments_db}
    driver-class-name: ${DB_DRIVER_CLASSNAME:org.postgresql.Driver}
    username: ${DR_USER:investor}
    password: ${DB_PASSWORD:investorpwd1234}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: InvestmentServiceJPACP
      max-lifetime: 2000000
      connection-timeout: 30000
  mail:
    host: localhost
    username:
    password:
    port: 1025

app:
  max-withdrawal-percentage: 90
  retirement-withdrawal-age: 65
  min-investor-age: 18
  email-configs:
    withdrawal:
      subject: Investment Withdrawal Confirmation!
      template-key: withdrawal.ftl
      from-email: withdrawals@investments.io

springdoc:
  swagger-ui:
    path: /swagger-ui.html