name: Investment Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v11
        with:
          servers:
            '[
              {
                "id": "github",
                "username": "${env.RELEASE_USERNAME}",
                "password": "${env.RELEASE_TOKEN}"
              }
            ]'
      - name: Build with Maven
        env:
          RELEASE_USERNAME: ${{ secrets.RELEASE_USERNAME }}
          RELEASEY_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          BUILD_ENV: 'github-actions'
        run: mvn clean install